// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: api/calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на расчет.
type CalculateRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          []*CalculateRequest_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_api_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetData() []*CalculateRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ответ на запрос расчета.
type CalculateResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*CalculateResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_api_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetItems() []*CalculateResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CalculateRequest_Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Тип инструкции
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Тип вычислительной операции
	Op *string `protobuf:"bytes,2,opt,name=op,proto3,oneof" json:"op,omitempty"`
	// Название переменной
	Var string `protobuf:"bytes,3,opt,name=var,proto3" json:"var,omitempty"`
	// Левое значение
	Left *string `protobuf:"bytes,4,opt,name=left,proto3,oneof" json:"left,omitempty"`
	// Правое значение
	Right         *string `protobuf:"bytes,5,opt,name=right,proto3,oneof" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest_Data) Reset() {
	*x = CalculateRequest_Data{}
	mi := &file_api_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest_Data) ProtoMessage() {}

func (x *CalculateRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest_Data.ProtoReflect.Descriptor instead.
func (*CalculateRequest_Data) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CalculateRequest_Data) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CalculateRequest_Data) GetOp() string {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return ""
}

func (x *CalculateRequest_Data) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *CalculateRequest_Data) GetLeft() string {
	if x != nil && x.Left != nil {
		return *x.Left
	}
	return ""
}

func (x *CalculateRequest_Data) GetRight() string {
	if x != nil && x.Right != nil {
		return *x.Right
	}
	return ""
}

type CalculateResponse_Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название переменной
	Var string `protobuf:"bytes,1,opt,name=var,proto3" json:"var,omitempty"`
	// Значение ответа
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse_Item) Reset() {
	*x = CalculateResponse_Item{}
	mi := &file_api_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse_Item) ProtoMessage() {}

func (x *CalculateResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse_Item.ProtoReflect.Descriptor instead.
func (*CalculateResponse_Item) Descriptor() ([]byte, []int) {
	return file_api_calculator_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CalculateResponse_Item) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *CalculateResponse_Item) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_calculator_proto protoreflect.FileDescriptor

var file_api_calculator_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0xdb, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x8f,
	0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x70, 0x88, 0x01, 0x01,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76,
	0x61, 0x72, 0x12, 0x17, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x6f, 0x70, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x7d, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a,
	0x2e, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32,
	0x58, 0x0a, 0x0a, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x3b, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_calculator_proto_rawDescOnce sync.Once
	file_api_calculator_proto_rawDescData []byte
)

func file_api_calculator_proto_rawDescGZIP() []byte {
	file_api_calculator_proto_rawDescOnce.Do(func() {
		file_api_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_calculator_proto_rawDesc), len(file_api_calculator_proto_rawDesc)))
	})
	return file_api_calculator_proto_rawDescData
}

var file_api_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_calculator_proto_goTypes = []any{
	(*CalculateRequest)(nil),       // 0: calculator.CalculateRequest
	(*CalculateResponse)(nil),      // 1: calculator.CalculateResponse
	(*CalculateRequest_Data)(nil),  // 2: calculator.CalculateRequest.Data
	(*CalculateResponse_Item)(nil), // 3: calculator.CalculateResponse.Item
}
var file_api_calculator_proto_depIdxs = []int32{
	2, // 0: calculator.CalculateRequest.data:type_name -> calculator.CalculateRequest.Data
	3, // 1: calculator.CalculateResponse.items:type_name -> calculator.CalculateResponse.Item
	0, // 2: calculator.URLService.Calculate:input_type -> calculator.CalculateRequest
	1, // 3: calculator.URLService.Calculate:output_type -> calculator.CalculateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_calculator_proto_init() }
func file_api_calculator_proto_init() {
	if File_api_calculator_proto != nil {
		return
	}
	file_api_calculator_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_calculator_proto_rawDesc), len(file_api_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_calculator_proto_goTypes,
		DependencyIndexes: file_api_calculator_proto_depIdxs,
		MessageInfos:      file_api_calculator_proto_msgTypes,
	}.Build()
	File_api_calculator_proto = out.File
	file_api_calculator_proto_goTypes = nil
	file_api_calculator_proto_depIdxs = nil
}
