definitions:
  model.Expression:
    properties:
      left:
        allOf:
        - $ref: '#/definitions/model.RawOperand'
        description: |-
          Левый операнд: либо число, либо имя переменной
          oneOf: [integer string]
          example: 10
      op:
        allOf:
        - $ref: '#/definitions/model.Operation'
        description: |-
          Тип вычислительной операции: +, -, *, /
          example: "+"
        example: +
      right:
        allOf:
        - $ref: '#/definitions/model.RawOperand'
        description: |-
          Правый операнд: либо число, либо имя переменной
          oneOf: [integer string]
          example: 20
      type:
        allOf:
        - $ref: '#/definitions/model.Type'
        description: |-
          Тип инструкции: calc – вычисление, print – вывод результата
          Enum: [calc print]
          required: true
        example: calc
      var:
        description: |-
          Название переменной, в которую записывается результат или печатаем
          required: true
          example: x
        example: x
        type: string
    type: object
  model.Operation:
    description: 'Арифметическая операция: +, -, *, /'
    enum:
    - Unknown
    - +
    - '-'
    - '*'
    - /
    type: string
    x-enum-varnames:
    - UnknownOperation
    - Addition
    - Subtraction
    - Multiplication
    - Division
  model.RawOperand:
    type: object
  model.Result:
    properties:
      value:
        description: |-
          Значение переменной
          required: true
          example: 42
        type: integer
      var:
        description: |-
          Название переменной, результат которой выводится
          required: true
          example: x
        type: string
    type: object
  model.Type:
    description: 'Тип операции: calc - вычисление, print - вывод результата'
    enum:
    - Unknown
    - calc
    - print
    type: string
    x-enum-varnames:
    - UnknownType
    - Calc
    - Print
info:
  contact: {}
paths:
  /api/calculate:
    post:
      consumes:
      - application/json
      description: |-
        Обрабатывает список инструкций:
        • calc – вычисляет арифметическую операцию (с эмуляцией задержки 50 ms)
        • print – возвращает значение переменной
      parameters:
      - description: Список инструкций calc/print
        in: body
        name: expressions
        required: true
        schema:
          items:
            $ref: '#/definitions/model.Expression'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Результаты print в порядке вызова
          schema:
            items:
              $ref: '#/definitions/model.Result'
            type: array
        "400":
          description: Ошибка валидации или выполнения
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Выполнить инструкции калькулятора
      tags:
      - Calculator
swagger: "2.0"
